version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stockmanagement-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockmanagement
      MYSQL_USER: stockuser
      MYSQL_PASSWORD: stockpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - stockmanagement-network

volumes:
  mysql-data:
    name: stockmanagement-mysql-data

networks:
  stockmanagement-network:
    name: stockmanagement-network 